version: '3'

services:
  rocketchat:
    image: rocket.chat:latest
    ports:
      - "3000:3000"
    environment:
      - ROOT_URL=http://localhost:3000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    command: mongod --smallfiles --oplogSize 128 --replSet rs0
