
FROM node:14
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
RUN apt-get update && apt-get install -y mongodb
EXPOSE 3000
EXPOSE 27017
CMD ["mongod", "--bind_ip_all"]
CMD ["npm", "start"]

